Add case-insensitive matching of known filenames and extensions
Peltoche/lsd pull request #383
Opened 2020-06-09 09:29 UTC by poita66

Although this achieves what I set out to do, I fully expect that there's a more idiomatic way of doing it, so I'm expecting changes to be requested

The main reason for this change is that I had a dockerfile that had a capital 'd' and therefore it didn't match anything in the known filename hash set. I figured that the same logic should apply to extensions, too

Feel free to reject this, too, as I know it's an edge case and some would argue that a dockerfile with a capital 'd' doesn't deserve to have a nice icon haha

2020-06-09 13:37 UTC, meain commented
@poita66 I am not sure if this is a good idea. For stuff like `Dockerfile`, it kinda makes sense, but I am not sure if ones like `NODE_MODULES` or `.GIT` should be treated same as their lower case counterpart.

It makes sense for extensions I guess.

2020-06-09 23:27 UTC, poita66 commented
@meain 
If it was for anything more important than choosing an icon, I'd totally agree. However, because that's all it affects, I figure that a NODE_MODULES folder should get a nice icon too.
It would also then mimic the behavior of VS Code (and I expect most editors), which puts an icon on files no matter the case-ness.

2020-09-30 04:37 UTC, meain commented
Hey, I think we could probably merge this in. As of now there is only `.Trash` in the actual list that has a capital letter.
So I think you could change that to `.trash` and then only check with `input.tolower()`.

This should also fix https://github.com/Peltoche/lsd/issues/420

2020-10-27 01:36 UTC, poita66 commented
Hey! Will do. Sorry about the late reply, I must've missed the notification email.

2020-10-27 12:18 UTC, meain commented
Hey, there seems to be some extra files that have been commited like `.Trash`, `.trash`, and `readme.md`.
Could you remove those. Also, could you rebase your work on top of current master.

2020-10-27 22:23 UTC, poita66 commented
Done!

2020-10-28 04:00 UTC, meain requested changes
@poita66 Could you also add a test to ensure both upper and lowercae filenames match.

2020-10-28 04:00 UTC, meain commented on src/icon.rs
> +                .get(String::from(extension).to_lowercase().as_str())
```suggestion
                .get(extension.to_lowercase().as_str())
```

2020-11-09 02:44 UTC, poita66 commented
@meain Tests have been added and your suggested changes have been incorporated and tested. Thanks for your help and sorry about the delay :sweat_smile:

2020-11-09 06:49 UTC, meain approved these changes
LGTM, thanks :)

2020-11-09 06:49 UTC, merged