Add option to not sort
Peltoche/lsd pull request #626
Opened 2022-02-20 17:49 UTC by MichaelAug

Add ls -U equivalent flag

closes #615 

#### TODO

- [X] Use `cargo fmt`
- [X] Add necessary tests
- [ ] Add changelog entry

2022-02-20 18:04 UTC, meain requested changes
Looks good, just have a few tiny nitpicks.

2022-02-20 18:04 UTC, meain commented on doc/lsd.md
> +: Do not sort
Just to keep it consistent with gnu ls.

```suggestion
: Do not sort. List entries in directory order
```

2022-02-21 08:09 UTC, MichaelAug commented
Thanks for the feedback! All comments addressed and changelog updated :)

2022-02-21 16:13 UTC, meain commented
LGTM. Thanks for working on this :D

2022-02-21 16:13 UTC, merged